using YouG.Application.Common.Interfaces;
using YouG.Domain.Entities;

namespace YouG.Application.Features.Availability.Jobs;

/// <summary>
/// Expands AvailabilityRules into materialized AvailabilityInstance rows for a rolling horizon
/// (docs/01-PRD.md Section 8, docs/02-ARCHITECTURE.md Section 5.2). Never overwrites an instance
/// that was manually edited (SourceRuleId == null) or generated by a different rule — only the
/// rule that originally produced a row is allowed to update it (docs/03-DATABASE.md Section 3.9).
/// </summary>
public class RecurrenceMaterializationJob(
    IAvailabilityRuleRepository ruleRepository,
    IAvailabilityInstanceRepository instanceRepository,
    IUnitOfWork unitOfWork,
    IDateTimeProvider dateTimeProvider) : IRecurrenceMaterializationJob
{
    private const int HorizonDays = 56; // ~8 weeks, per the Phase 1 decision

    public async Task RunForUserAsync(Guid userId, CancellationToken cancellationToken)
    {
        var rules = await ruleRepository.GetByUserIdAsync(userId, cancellationToken);

        if (rules.Count == 0)
        {
            return;
        }

        await MaterializeAsync(userId, rules, cancellationToken);
        await unitOfWork.SaveChangesAsync(cancellationToken);
    }

    public async Task RunFullSweepAsync(CancellationToken cancellationToken)
    {
        var rulesByUser = (await ruleRepository.GetAllAsync(cancellationToken)).GroupBy(r => r.UserId);

        foreach (var group in rulesByUser)
        {
            await MaterializeAsync(group.Key, group.ToList(), cancellationToken);
        }

        await unitOfWork.SaveChangesAsync(cancellationToken);
    }

    private async Task MaterializeAsync(Guid userId, List<AvailabilityRule> rules, CancellationToken cancellationToken)
    {
        var today = DateOnly.FromDateTime(dateTimeProvider.UtcNow.UtcDateTime);
        var horizonEnd = today.AddDays(HorizonDays);

        var existingList = await instanceRepository.GetForUserInRangeAsync(userId, today, horizonEnd, cancellationToken);
        var existingInstances = existingList.ToDictionary(i => (i.Date, i.Daypart));

        var now = dateTimeProvider.UtcNow;

        foreach (var rule in rules)
        {
            for (var date = LatestOf(today, rule.EffectiveFrom); date <= horizonEnd; date = date.AddDays(1))
            {
                if (date.DayOfWeek != rule.DayOfWeek)
                {
                    continue;
                }

                if (rule.EffectiveUntil.HasValue && date > rule.EffectiveUntil.Value)
                {
                    break;
                }

                var key = (date, rule.Daypart);

                if (existingInstances.TryGetValue(key, out var existing))
                {
                    if (existing.SourceRuleId == rule.Id && existing.Status != rule.Status)
                    {
                        existing.Status = rule.Status;
                        existing.UpdatedAt = now;
                    }

                    // Otherwise: a manual override (SourceRuleId == null) or another rule's
                    // instance already occupies this slot — leave it untouched.
                }
                else
                {
                    var instance = new AvailabilityInstance
                    {
                        UserId = userId,
                        Date = date,
                        Daypart = rule.Daypart,
                        Status = rule.Status,
                        SourceRuleId = rule.Id,
                        UpdatedAt = now
                    };

                    instanceRepository.Add(instance);
                    existingInstances[key] = instance;
                }
            }
        }
    }

    private static DateOnly LatestOf(DateOnly a, DateOnly b) => a > b ? a : b;
}
