// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkz2DPoFyZ1FK3olJ4kbIF6Wij1EcTdQ4',
    appId: '1:94600500115:web:fb14c644d03f858bb94e66',
    messagingSenderId: '94600500115',
    projectId: 'you-g-f0698',
    authDomain: 'you-g-f0698.firebaseapp.com',
    storageBucket: 'you-g-f0698.firebasestorage.app',
    measurementId: 'G-S0H4N45DXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49ip0pOAGis9OUbE5DEJRGsdI-DRS5ks',
    appId: '1:94600500115:android:e74b54bce901a17db94e66',
    messagingSenderId: '94600500115',
    projectId: 'you-g-f0698',
    storageBucket: 'you-g-f0698.firebasestorage.app',
  );
}
